import type { Metadata } from "next";
import { Alef } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "./contexts/LanguageContext";
import Headers from "./components/Header";
import Footer from "./components/Footer";

const alef = Alef({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-alef",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alef.variable}  antialiased`}>
        <LanguageProvider>
          <Headers />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
