import type { Metadata } from "next";
import { Alef } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "./contexts/LanguageContext";


const alef = Alef({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-alef",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add this to avoid unnecessary preloading */}
        <meta name="next-size-adjust" />
      </head>
      <body className={`${alef.variable}  antialiased`}>
        <LanguageProvider>
       
          {children}
      
        </LanguageProvider>
      </body>
    </html>
  );
}
